/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAPIKeyOwnerType.h
 *
 * An enumeration.
 */

#ifndef OAIAPIKeyOwnerType_H
#define OAIAPIKeyOwnerType_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIAPIKeyOwnerType : public OAIEnum {
public:
    OAIAPIKeyOwnerType();
    OAIAPIKeyOwnerType(QString json);
    ~OAIAPIKeyOwnerType() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIAPIKeyOwnerType {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        PDP_CONFIG, 
        MEMBER, 
        ELEMENTS
    };
    OAIAPIKeyOwnerType::eOAIAPIKeyOwnerType getValue() const;
    void setValue(const OAIAPIKeyOwnerType::eOAIAPIKeyOwnerType& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIAPIKeyOwnerType m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIAPIKeyOwnerType)

#endif // OAIAPIKeyOwnerType_H
