/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIConditionSetCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIConditionSetCreate::OAIConditionSetCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIConditionSetCreate::OAIConditionSetCreate() {
    this->initializeModel();
}

OAIConditionSetCreate::~OAIConditionSetCreate() {}

void OAIConditionSetCreate::initializeModel() {

    m_key_isSet = false;
    m_key_isValid = false;

    m_type_isSet = false;
    m_type_isValid = false;

    m_autogenerated_isSet = false;
    m_autogenerated_isValid = false;

    m_resource_id_isSet = false;
    m_resource_id_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_conditions_isSet = false;
    m_conditions_isValid = false;
}

void OAIConditionSetCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIConditionSetCreate::fromJsonObject(QJsonObject json) {

    m_key_isValid = ::OpenAPI::fromJsonValue(key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_type_isValid = ::OpenAPI::fromJsonValue(type, json[QString("type")]);
    m_type_isSet = !json[QString("type")].isNull() && m_type_isValid;

    m_autogenerated_isValid = ::OpenAPI::fromJsonValue(autogenerated, json[QString("autogenerated")]);
    m_autogenerated_isSet = !json[QString("autogenerated")].isNull() && m_autogenerated_isValid;

    m_resource_id_isValid = ::OpenAPI::fromJsonValue(resource_id, json[QString("resource_id")]);
    m_resource_id_isSet = !json[QString("resource_id")].isNull() && m_resource_id_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_description_isValid = ::OpenAPI::fromJsonValue(description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_conditions_isValid = ::OpenAPI::fromJsonValue(conditions, json[QString("conditions")]);
    m_conditions_isSet = !json[QString("conditions")].isNull() && m_conditions_isValid;
}

QString OAIConditionSetCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIConditionSetCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(key));
    }
    if (type.isSet()) {
        obj.insert(QString("type"), ::OpenAPI::toJsonValue(type));
    }
    if (m_autogenerated_isSet) {
        obj.insert(QString("autogenerated"), ::OpenAPI::toJsonValue(autogenerated));
    }
    if (resource_id.isSet()) {
        obj.insert(QString("resource_id"), ::OpenAPI::toJsonValue(resource_id));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::OpenAPI::toJsonValue(description));
    }
    if (m_conditions_isSet) {
        obj.insert(QString("conditions"), ::OpenAPI::toJsonValue(conditions));
    }
    return obj;
}

QString OAIConditionSetCreate::getKey() const {
    return key;
}
void OAIConditionSetCreate::setKey(const QString &key) {
    this->key = key;
    this->m_key_isSet = true;
}

bool OAIConditionSetCreate::is_key_Set() const{
    return m_key_isSet;
}

bool OAIConditionSetCreate::is_key_Valid() const{
    return m_key_isValid;
}

OAIConditionSetType OAIConditionSetCreate::getType() const {
    return type;
}
void OAIConditionSetCreate::setType(const OAIConditionSetType &type) {
    this->type = type;
    this->m_type_isSet = true;
}

bool OAIConditionSetCreate::is_type_Set() const{
    return m_type_isSet;
}

bool OAIConditionSetCreate::is_type_Valid() const{
    return m_type_isValid;
}

bool OAIConditionSetCreate::isAutogenerated() const {
    return autogenerated;
}
void OAIConditionSetCreate::setAutogenerated(const bool &autogenerated) {
    this->autogenerated = autogenerated;
    this->m_autogenerated_isSet = true;
}

bool OAIConditionSetCreate::is_autogenerated_Set() const{
    return m_autogenerated_isSet;
}

bool OAIConditionSetCreate::is_autogenerated_Valid() const{
    return m_autogenerated_isValid;
}

OAIResource_Id OAIConditionSetCreate::getResourceId() const {
    return resource_id;
}
void OAIConditionSetCreate::setResourceId(const OAIResource_Id &resource_id) {
    this->resource_id = resource_id;
    this->m_resource_id_isSet = true;
}

bool OAIConditionSetCreate::is_resource_id_Set() const{
    return m_resource_id_isSet;
}

bool OAIConditionSetCreate::is_resource_id_Valid() const{
    return m_resource_id_isValid;
}

QString OAIConditionSetCreate::getName() const {
    return name;
}
void OAIConditionSetCreate::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAIConditionSetCreate::is_name_Set() const{
    return m_name_isSet;
}

bool OAIConditionSetCreate::is_name_Valid() const{
    return m_name_isValid;
}

QString OAIConditionSetCreate::getDescription() const {
    return description;
}
void OAIConditionSetCreate::setDescription(const QString &description) {
    this->description = description;
    this->m_description_isSet = true;
}

bool OAIConditionSetCreate::is_description_Set() const{
    return m_description_isSet;
}

bool OAIConditionSetCreate::is_description_Valid() const{
    return m_description_isValid;
}

OAIObject OAIConditionSetCreate::getConditions() const {
    return conditions;
}
void OAIConditionSetCreate::setConditions(const OAIObject &conditions) {
    this->conditions = conditions;
    this->m_conditions_isSet = true;
}

bool OAIConditionSetCreate::is_conditions_Set() const{
    return m_conditions_isSet;
}

bool OAIConditionSetCreate::is_conditions_Valid() const{
    return m_conditions_isValid;
}

bool OAIConditionSetCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (type.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_autogenerated_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (resource_id.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_conditions_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIConditionSetCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_key_isValid && m_name_isValid && true;
}

} // namespace OpenAPI
