/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIConditionSetCreate.h
 *
 * 
 */

#ifndef OAIConditionSetCreate_H
#define OAIConditionSetCreate_H

#include <QJsonObject>

#include "OAIConditionSetType.h"
#include "OAIObject.h"
#include "OAIResource_Id.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIConditionSetCreate : public OAIObject {
public:
    OAIConditionSetCreate();
    OAIConditionSetCreate(QString json);
    ~OAIConditionSetCreate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getKey() const;
    void setKey(const QString &key);
    bool is_key_Set() const;
    bool is_key_Valid() const;

    OAIConditionSetType getType() const;
    void setType(const OAIConditionSetType &type);
    bool is_type_Set() const;
    bool is_type_Valid() const;

    bool isAutogenerated() const;
    void setAutogenerated(const bool &autogenerated);
    bool is_autogenerated_Set() const;
    bool is_autogenerated_Valid() const;

    OAIResource_Id getResourceId() const;
    void setResourceId(const OAIResource_Id &resource_id);
    bool is_resource_id_Set() const;
    bool is_resource_id_Valid() const;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getDescription() const;
    void setDescription(const QString &description);
    bool is_description_Set() const;
    bool is_description_Valid() const;

    OAIObject getConditions() const;
    void setConditions(const OAIObject &conditions);
    bool is_conditions_Set() const;
    bool is_conditions_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString key;
    bool m_key_isSet;
    bool m_key_isValid;

    OAIConditionSetType type;
    bool m_type_isSet;
    bool m_type_isValid;

    bool autogenerated;
    bool m_autogenerated_isSet;
    bool m_autogenerated_isValid;

    OAIResource_Id resource_id;
    bool m_resource_id_isSet;
    bool m_resource_id_isValid;

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString description;
    bool m_description_isSet;
    bool m_description_isValid;

    OAIObject conditions;
    bool m_conditions_isSet;
    bool m_conditions_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIConditionSetCreate)

#endif // OAIConditionSetCreate_H
