/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIConditionSetRulesApi_H
#define OAI_OAIConditionSetRulesApi_H

#include "OAIHelpers.h"
#include "OAIHttpRequest.h"
#include "OAIServerConfiguration.h"
#include "OAIOauth.h"

#include "OAIConditionSetRuleCreate.h"
#include "OAIConditionSetRuleRead.h"
#include "OAIConditionSetRuleRemove.h"
#include "OAIHTTPValidationError.h"
#include <QString>

#include <QObject>
#include <QByteArray>
#include <QStringList>
#include <QList>
#include <QNetworkAccessManager>

namespace OpenAPI {

class OAIConditionSetRulesApi : public QObject {
    Q_OBJECT

public:
    OAIConditionSetRulesApi(const int timeOut = 0);
    ~OAIConditionSetRulesApi();

    void initializeServerConfigs();
    int setDefaultServerValue(int serverIndex,const QString &operation, const QString &variable,const QString &val);
    void setServerIndex(const QString &operation, int serverIndex);
    void setApiKey(const QString &apiKeyName, const QString &apiKey);
    void setBearerToken(const QString &token);
    void setUsername(const QString &username);
    void setPassword(const QString &password);
    void setTimeOut(const int timeOut);
    void setWorkingDirectory(const QString &path);
    void setNetworkAccessManager(QNetworkAccessManager* manager);
    int addServerConfiguration(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables = QMap<QString, OAIServerVariable>());
    void setNewServerForAllOperations(const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void setNewServer(const QString &operation, const QUrl &url, const QString &description = "", const QMap<QString, OAIServerVariable> &variables =  QMap<QString, OAIServerVariable>());
    void addHeaders(const QString &key, const QString &value);
    void enableRequestCompression();
    void enableResponseCompression();
    void abortRequests();
    QString getParamStylePrefix(const QString &style);
    QString getParamStyleSuffix(const QString &style);
    QString getParamStyleDelimiter(const QString &style, const QString &name, bool isExplode);

    /**
    * @param[in]  proj_id QString [required]
    * @param[in]  env_id QString [required]
    * @param[in]  oai_condition_set_rule_create OAIConditionSetRuleCreate [required]
    */
    void assignSetPermissions(const QString &proj_id, const QString &env_id, const OAIConditionSetRuleCreate &oai_condition_set_rule_create);

    /**
    * @param[in]  proj_id QString [required]
    * @param[in]  env_id QString [required]
    * @param[in]  user_set QString [optional]
    * @param[in]  permission QString [optional]
    * @param[in]  resource_set QString [optional]
    * @param[in]  page qint32 [optional]
    * @param[in]  per_page qint32 [optional]
    */
    void listSetPermissions(const QString &proj_id, const QString &env_id, const ::OpenAPI::OptionalParam<QString> &user_set = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &permission = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<QString> &resource_set = ::OpenAPI::OptionalParam<QString>(), const ::OpenAPI::OptionalParam<qint32> &page = ::OpenAPI::OptionalParam<qint32>(), const ::OpenAPI::OptionalParam<qint32> &per_page = ::OpenAPI::OptionalParam<qint32>());

    /**
    * @param[in]  proj_id QString [required]
    * @param[in]  env_id QString [required]
    * @param[in]  oai_condition_set_rule_remove OAIConditionSetRuleRemove [required]
    */
    void unassignSetPermissions(const QString &proj_id, const QString &env_id, const OAIConditionSetRuleRemove &oai_condition_set_rule_remove);


private:
    QMap<QString,int> _serverIndices;
    QMap<QString,QList<OAIServerConfiguration>> _serverConfigs;
    QMap<QString, QString> _apiKeys;
    QString _bearerToken;
    QString _username;
    QString _password;
    int _timeOut;
    QString _workingDirectory;
    QNetworkAccessManager* _manager;
    QMap<QString, QString> _defaultHeaders;
    bool _isResponseCompressionEnabled;
    bool _isRequestCompressionEnabled;
    OAIHttpRequestInput _latestInput;
    OAIHttpRequestWorker *_latestWorker;
    QStringList _latestScope;
    OauthCode _authFlow;
    OauthImplicit _implicitFlow;
    OauthCredentials _credentialFlow;
    OauthPassword _passwordFlow;
    int _OauthMethod = 0;

    void assignSetPermissionsCallback(OAIHttpRequestWorker *worker);
    void listSetPermissionsCallback(OAIHttpRequestWorker *worker);
    void unassignSetPermissionsCallback(OAIHttpRequestWorker *worker);

signals:

    void assignSetPermissionsSignal(QList<OAIConditionSetRuleRead> summary);
    void listSetPermissionsSignal(QList<OAIConditionSetRuleRead> summary);
    void unassignSetPermissionsSignal();

    void assignSetPermissionsSignalFull(OAIHttpRequestWorker *worker, QList<OAIConditionSetRuleRead> summary);
    void listSetPermissionsSignalFull(OAIHttpRequestWorker *worker, QList<OAIConditionSetRuleRead> summary);
    void unassignSetPermissionsSignalFull(OAIHttpRequestWorker *worker);

    void assignSetPermissionsSignalE(QList<OAIConditionSetRuleRead> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void listSetPermissionsSignalE(QList<OAIConditionSetRuleRead> summary, QNetworkReply::NetworkError error_type, QString error_str);
    void unassignSetPermissionsSignalE(QNetworkReply::NetworkError error_type, QString error_str);

    void assignSetPermissionsSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void listSetPermissionsSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);
    void unassignSetPermissionsSignalEFull(OAIHttpRequestWorker *worker, QNetworkReply::NetworkError error_type, QString error_str);

    void abortRequestsSignal();
    void allPendingRequestsCompleted();

public slots:
    void tokenAvailable();
    
};

} // namespace OpenAPI
#endif
