/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIElementsConfigCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIElementsConfigCreate::OAIElementsConfigCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIElementsConfigCreate::OAIElementsConfigCreate() {
    this->initializeModel();
}

OAIElementsConfigCreate::~OAIElementsConfigCreate() {}

void OAIElementsConfigCreate::initializeModel() {

    m_key_isSet = false;
    m_key_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_elements_type_isSet = false;
    m_elements_type_isValid = false;

    m_settings_isSet = false;
    m_settings_isValid = false;

    m_roles_to_levels_isSet = false;
    m_roles_to_levels_isValid = false;

    m_webhook_isSet = false;
    m_webhook_isValid = false;
}

void OAIElementsConfigCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIElementsConfigCreate::fromJsonObject(QJsonObject json) {

    m_key_isValid = ::OpenAPI::fromJsonValue(key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_elements_type_isValid = ::OpenAPI::fromJsonValue(elements_type, json[QString("elements_type")]);
    m_elements_type_isSet = !json[QString("elements_type")].isNull() && m_elements_type_isValid;

    m_settings_isValid = ::OpenAPI::fromJsonValue(settings, json[QString("settings")]);
    m_settings_isSet = !json[QString("settings")].isNull() && m_settings_isValid;

    if(json["roles_to_levels"].isObject()){
        auto varmap = json["roles_to_levels"].toObject().toVariantMap();
        m_roles_to_levels_isValid = true;
        if(varmap.count() > 0){
            for(auto val : varmap.keys()){
                QList<QString> item;
                auto jval = QJsonValue::fromVariant(varmap.value(val));
                m_roles_to_levels_isValid &= ::OpenAPI::fromJsonValue(item, jval);
                m_roles_to_levels_isSet &= !jval.isNull() && m_roles_to_levels_isValid;
                roles_to_levels.insert(roles_to_levels.end(), val, item);
            }
        }
    }

    m_webhook_isValid = ::OpenAPI::fromJsonValue(webhook, json[QString("webhook")]);
    m_webhook_isSet = !json[QString("webhook")].isNull() && m_webhook_isValid;
}

QString OAIElementsConfigCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIElementsConfigCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(key));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (elements_type.isSet()) {
        obj.insert(QString("elements_type"), ::OpenAPI::toJsonValue(elements_type));
    }
    if (settings.size() > 0) {
        obj.insert(QString("settings"), ::OpenAPI::toJsonValue(settings));
    }
    if (roles_to_levels.size() > 0) {
        
        obj.insert(QString("roles_to_levels"), toJsonValue(roles_to_levels));
    }
    if (webhook.isSet()) {
        obj.insert(QString("webhook"), ::OpenAPI::toJsonValue(webhook));
    }
    return obj;
}

QString OAIElementsConfigCreate::getKey() const {
    return key;
}
void OAIElementsConfigCreate::setKey(const QString &key) {
    this->key = key;
    this->m_key_isSet = true;
}

bool OAIElementsConfigCreate::is_key_Set() const{
    return m_key_isSet;
}

bool OAIElementsConfigCreate::is_key_Valid() const{
    return m_key_isValid;
}

QString OAIElementsConfigCreate::getName() const {
    return name;
}
void OAIElementsConfigCreate::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAIElementsConfigCreate::is_name_Set() const{
    return m_name_isSet;
}

bool OAIElementsConfigCreate::is_name_Valid() const{
    return m_name_isValid;
}

OAIElementsType OAIElementsConfigCreate::getElementsType() const {
    return elements_type;
}
void OAIElementsConfigCreate::setElementsType(const OAIElementsType &elements_type) {
    this->elements_type = elements_type;
    this->m_elements_type_isSet = true;
}

bool OAIElementsConfigCreate::is_elements_type_Set() const{
    return m_elements_type_isSet;
}

bool OAIElementsConfigCreate::is_elements_type_Valid() const{
    return m_elements_type_isValid;
}

QMap<QString, OAISettings> OAIElementsConfigCreate::getSettings() const {
    return settings;
}
void OAIElementsConfigCreate::setSettings(const QMap<QString, OAISettings> &settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}

bool OAIElementsConfigCreate::is_settings_Set() const{
    return m_settings_isSet;
}

bool OAIElementsConfigCreate::is_settings_Valid() const{
    return m_settings_isValid;
}

QMap<QString, QList<QString>> OAIElementsConfigCreate::getRolesToLevels() const {
    return roles_to_levels;
}
void OAIElementsConfigCreate::setRolesToLevels(const QMap<QString, QList<QString>> &roles_to_levels) {
    this->roles_to_levels = roles_to_levels;
    this->m_roles_to_levels_isSet = true;
}

bool OAIElementsConfigCreate::is_roles_to_levels_Set() const{
    return m_roles_to_levels_isSet;
}

bool OAIElementsConfigCreate::is_roles_to_levels_Valid() const{
    return m_roles_to_levels_isValid;
}

OAIWebhookCreate OAIElementsConfigCreate::getWebhook() const {
    return webhook;
}
void OAIElementsConfigCreate::setWebhook(const OAIWebhookCreate &webhook) {
    this->webhook = webhook;
    this->m_webhook_isSet = true;
}

bool OAIElementsConfigCreate::is_webhook_Set() const{
    return m_webhook_isSet;
}

bool OAIElementsConfigCreate::is_webhook_Valid() const{
    return m_webhook_isValid;
}

bool OAIElementsConfigCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (elements_type.isSet()) {
            isObjectUpdated = true;
            break;
        }

        if (settings.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (roles_to_levels.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (webhook.isSet()) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIElementsConfigCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_key_isValid && m_name_isValid && m_elements_type_isValid && m_settings_isValid && m_roles_to_levels_isValid && true;
}

} // namespace OpenAPI
