/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIEnvironmentUpdate.h
 *
 * 
 */

#ifndef OAIEnvironmentUpdate_H
#define OAIEnvironmentUpdate_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIEnvironmentUpdate : public OAIObject {
public:
    OAIEnvironmentUpdate();
    OAIEnvironmentUpdate(QString json);
    ~OAIEnvironmentUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getDescription() const;
    void setDescription(const QString &description);
    bool is_description_Set() const;
    bool is_description_Valid() const;

    QString getCustomBranchName() const;
    void setCustomBranchName(const QString &custom_branch_name);
    bool is_custom_branch_name_Set() const;
    bool is_custom_branch_name_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString description;
    bool m_description_isSet;
    bool m_description_isValid;

    QString custom_branch_name;
    bool m_custom_branch_name_isSet;
    bool m_custom_branch_name_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIEnvironmentUpdate)

#endif // OAIEnvironmentUpdate_H
