/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIElementsEnvTypeUpdate.h
 *
 * 
 */

#ifndef OAIElementsEnvTypeUpdate_H
#define OAIElementsEnvTypeUpdate_H

#include <QJsonObject>

#include <QList>
#include <QMap>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIElementsEnvTypeUpdate : public OAIObject {
public:
    OAIElementsEnvTypeUpdate();
    OAIElementsEnvTypeUpdate(QString json);
    ~OAIElementsEnvTypeUpdate() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QMap<QString, QList<QString>> getRolesToLevels() const;
    void setRolesToLevels(const QMap<QString, QList<QString>> &roles_to_levels);
    bool is_roles_to_levels_Set() const;
    bool is_roles_to_levels_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QMap<QString, QList<QString>> roles_to_levels;
    bool m_roles_to_levels_isSet;
    bool m_roles_to_levels_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIElementsEnvTypeUpdate)

#endif // OAIElementsEnvTypeUpdate_H
