/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIElementsType.h
 *
 * An enumeration.
 */

#ifndef OAIElementsType_H
#define OAIElementsType_H

#include <QJsonObject>


#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIElementsType : public OAIEnum {
public:
    OAIElementsType();
    OAIElementsType(QString json);
    ~OAIElementsType() override;

    QString asJson() const override;
    QJsonValue asJsonValue() const override;
    void fromJsonValue(QJsonValue json) override;
    void fromJson(QString jsonString) override;

    enum class eOAIElementsType {
        INVALID_VALUE_OPENAPI_GENERATED = 0,
        USER_MANAGEMENT, 
        AUDIT_LOG, 
        APPROVAL_FLOW
    };
    OAIElementsType::eOAIElementsType getValue() const;
    void setValue(const OAIElementsType::eOAIElementsType& value);
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    eOAIElementsType m_value;
    bool m_value_isSet;
    bool m_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIElementsType)

#endif // OAIElementsType_H
