/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIEmbeddedLoginRequestOutput.h
 *
 * 
 */

#ifndef OAIEmbeddedLoginRequestOutput_H
#define OAIEmbeddedLoginRequestOutput_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIEmbeddedLoginRequestOutput : public OAIObject {
public:
    OAIEmbeddedLoginRequestOutput();
    OAIEmbeddedLoginRequestOutput(QString json);
    ~OAIEmbeddedLoginRequestOutput() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getError() const;
    void setError(const QString &error);
    bool is_error_Set() const;
    bool is_error_Valid() const;

    qint32 getErrorCode() const;
    void setErrorCode(const qint32 &error_code);
    bool is_error_code_Set() const;
    bool is_error_code_Valid() const;

    QString getToken() const;
    void setToken(const QString &token);
    bool is_token_Set() const;
    bool is_token_Valid() const;

    QString getExtra() const;
    void setExtra(const QString &extra);
    bool is_extra_Set() const;
    bool is_extra_Valid() const;

    QString getRedirectUrl() const;
    void setRedirectUrl(const QString &redirect_url);
    bool is_redirect_url_Set() const;
    bool is_redirect_url_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString error;
    bool m_error_isSet;
    bool m_error_isValid;

    qint32 error_code;
    bool m_error_code_isSet;
    bool m_error_code_isValid;

    QString token;
    bool m_token_isSet;
    bool m_token_isValid;

    QString extra;
    bool m_extra_isSet;
    bool m_extra_isValid;

    QString redirect_url;
    bool m_redirect_url_isSet;
    bool m_redirect_url_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIEmbeddedLoginRequestOutput)

#endif // OAIEmbeddedLoginRequestOutput_H
