/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILanguageInstructions.h
 *
 * 
 */

#ifndef OAILanguageInstructions_H
#define OAILanguageInstructions_H

#include <QJsonObject>

#include "OAIProgrammingLanguage.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAILanguageInstructions : public OAIObject {
public:
    OAILanguageInstructions();
    OAILanguageInstructions(QString json);
    ~OAILanguageInstructions() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIProgrammingLanguage getLanguage() const;
    void setLanguage(const OAIProgrammingLanguage &language);
    bool is_language_Set() const;
    bool is_language_Valid() const;

    QString getLabel() const;
    void setLabel(const QString &label);
    bool is_label_Set() const;
    bool is_label_Valid() const;

    QString getInstructions() const;
    void setInstructions(const QString &instructions);
    bool is_instructions_Set() const;
    bool is_instructions_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIProgrammingLanguage language;
    bool m_language_isSet;
    bool m_language_isValid;

    QString label;
    bool m_label_isSet;
    bool m_label_isValid;

    QString instructions;
    bool m_instructions_isSet;
    bool m_instructions_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAILanguageInstructions)

#endif // OAILanguageInstructions_H
