/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIMultiInviteResult.h
 *
 * 
 */

#ifndef OAIMultiInviteResult_H
#define OAIMultiInviteResult_H

#include <QJsonObject>

#include "OAIFailedInvite.h"
#include "OAIInviteRead.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIInviteRead;
class OAIFailedInvite;

class OAIMultiInviteResult : public OAIObject {
public:
    OAIMultiInviteResult();
    OAIMultiInviteResult(QString json);
    ~OAIMultiInviteResult() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QList<OAIInviteRead> getSuccess() const;
    void setSuccess(const QList<OAIInviteRead> &success);
    bool is_success_Set() const;
    bool is_success_Valid() const;

    QList<OAIFailedInvite> getFailed() const;
    void setFailed(const QList<OAIFailedInvite> &failed);
    bool is_failed_Set() const;
    bool is_failed_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QList<OAIInviteRead> success;
    bool m_success_isSet;
    bool m_success_isValid;

    QList<OAIFailedInvite> failed;
    bool m_failed_isSet;
    bool m_failed_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIMultiInviteResult)

#endif // OAIMultiInviteResult_H
