/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPDPContext.h
 *
 * 
 */

#ifndef OAIPDPContext_H
#define OAIPDPContext_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIPDPContext : public OAIObject {
public:
    OAIPDPContext();
    OAIPDPContext(QString json);
    ~OAIPDPContext() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getCustomerId() const;
    void setCustomerId(const QString &customer_id);
    bool is_customer_id_Set() const;
    bool is_customer_id_Valid() const;

    QString getClientId() const;
    void setClientId(const QString &client_id);
    bool is_client_id_Set() const;
    bool is_client_id_Valid() const;

    QString getBackendTier() const;
    void setBackendTier(const QString &backend_tier);
    bool is_backend_tier_Set() const;
    bool is_backend_tier_Valid() const;

    QString getComponent() const;
    void setComponent(const QString &component);
    bool is_component_Set() const;
    bool is_component_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString customer_id;
    bool m_customer_id_isSet;
    bool m_customer_id_isValid;

    QString client_id;
    bool m_client_id_isSet;
    bool m_client_id_isValid;

    QString backend_tier;
    bool m_backend_tier_isSet;
    bool m_backend_tier_isValid;

    QString component;
    bool m_component_isSet;
    bool m_component_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIPDPContext)

#endif // OAIPDPContext_H
