/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIProjectUpdate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIProjectUpdate::OAIProjectUpdate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIProjectUpdate::OAIProjectUpdate() {
    this->initializeModel();
}

OAIProjectUpdate::~OAIProjectUpdate() {}

void OAIProjectUpdate::initializeModel() {

    m_name_isSet = false;
    m_name_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_settings_isSet = false;
    m_settings_isValid = false;

    m_active_policy_repo_id_isSet = false;
    m_active_policy_repo_id_isValid = false;
}

void OAIProjectUpdate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIProjectUpdate::fromJsonObject(QJsonObject json) {

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_description_isValid = ::OpenAPI::fromJsonValue(description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_settings_isValid = ::OpenAPI::fromJsonValue(settings, json[QString("settings")]);
    m_settings_isSet = !json[QString("settings")].isNull() && m_settings_isValid;

    m_active_policy_repo_id_isValid = ::OpenAPI::fromJsonValue(active_policy_repo_id, json[QString("active_policy_repo_id")]);
    m_active_policy_repo_id_isSet = !json[QString("active_policy_repo_id")].isNull() && m_active_policy_repo_id_isValid;
}

QString OAIProjectUpdate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIProjectUpdate::asJsonObject() const {
    QJsonObject obj;
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::OpenAPI::toJsonValue(description));
    }
    if (m_settings_isSet) {
        obj.insert(QString("settings"), ::OpenAPI::toJsonValue(settings));
    }
    if (m_active_policy_repo_id_isSet) {
        obj.insert(QString("active_policy_repo_id"), ::OpenAPI::toJsonValue(active_policy_repo_id));
    }
    return obj;
}

QString OAIProjectUpdate::getName() const {
    return name;
}
void OAIProjectUpdate::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAIProjectUpdate::is_name_Set() const{
    return m_name_isSet;
}

bool OAIProjectUpdate::is_name_Valid() const{
    return m_name_isValid;
}

QString OAIProjectUpdate::getDescription() const {
    return description;
}
void OAIProjectUpdate::setDescription(const QString &description) {
    this->description = description;
    this->m_description_isSet = true;
}

bool OAIProjectUpdate::is_description_Set() const{
    return m_description_isSet;
}

bool OAIProjectUpdate::is_description_Valid() const{
    return m_description_isValid;
}

OAIObject OAIProjectUpdate::getSettings() const {
    return settings;
}
void OAIProjectUpdate::setSettings(const OAIObject &settings) {
    this->settings = settings;
    this->m_settings_isSet = true;
}

bool OAIProjectUpdate::is_settings_Set() const{
    return m_settings_isSet;
}

bool OAIProjectUpdate::is_settings_Valid() const{
    return m_settings_isValid;
}

QString OAIProjectUpdate::getActivePolicyRepoId() const {
    return active_policy_repo_id;
}
void OAIProjectUpdate::setActivePolicyRepoId(const QString &active_policy_repo_id) {
    this->active_policy_repo_id = active_policy_repo_id;
    this->m_active_policy_repo_id_isSet = true;
}

bool OAIProjectUpdate::is_active_policy_repo_id_Set() const{
    return m_active_policy_repo_id_isSet;
}

bool OAIProjectUpdate::is_active_policy_repo_id_Valid() const{
    return m_active_policy_repo_id_isValid;
}

bool OAIProjectUpdate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_settings_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_active_policy_repo_id_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIProjectUpdate::isValid() const {
    // only required properties are required for the object to be considered valid
    return true;
}

} // namespace OpenAPI
