/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRemoteConfig.h
 *
 * 
 */

#ifndef OAIRemoteConfig_H
#define OAIRemoteConfig_H

#include <QJsonObject>

#include "OAIOPALClient.h"
#include "OAIObject.h"
#include "OAIPDPContext.h"
#include "OAIPdp.h"

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {
class OAIOPALClient;
class OAIPdp;
class OAIPDPContext;

class OAIRemoteConfig : public OAIObject {
public:
    OAIRemoteConfig();
    OAIRemoteConfig(QString json);
    ~OAIRemoteConfig() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    OAIObject getOpalCommon() const;
    void setOpalCommon(const OAIObject &opal_common);
    bool is_opal_common_Set() const;
    bool is_opal_common_Valid() const;

    OAIOPALClient getOpalClient() const;
    void setOpalClient(const OAIOPALClient &opal_client);
    bool is_opal_client_Set() const;
    bool is_opal_client_Valid() const;

    OAIPdp getPdp() const;
    void setPdp(const OAIPdp &pdp);
    bool is_pdp_Set() const;
    bool is_pdp_Valid() const;

    OAIPDPContext getContext() const;
    void setContext(const OAIPDPContext &context);
    bool is_context_Set() const;
    bool is_context_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    OAIObject opal_common;
    bool m_opal_common_isSet;
    bool m_opal_common_isValid;

    OAIOPALClient opal_client;
    bool m_opal_client_isSet;
    bool m_opal_client_isValid;

    OAIPdp pdp;
    bool m_pdp_isSet;
    bool m_pdp_isValid;

    OAIPDPContext context;
    bool m_context_isSet;
    bool m_context_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRemoteConfig)

#endif // OAIRemoteConfig_H
