/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIResourceRead.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIResourceRead::OAIResourceRead(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIResourceRead::OAIResourceRead() {
    this->initializeModel();
}

OAIResourceRead::~OAIResourceRead() {}

void OAIResourceRead::initializeModel() {

    m_key_isSet = false;
    m_key_isValid = false;

    m_id_isSet = false;
    m_id_isValid = false;

    m_organization_id_isSet = false;
    m_organization_id_isValid = false;

    m_project_id_isSet = false;
    m_project_id_isValid = false;

    m_environment_id_isSet = false;
    m_environment_id_isValid = false;

    m_created_at_isSet = false;
    m_created_at_isValid = false;

    m_updated_at_isSet = false;
    m_updated_at_isValid = false;

    m_name_isSet = false;
    m_name_isValid = false;

    m_urn_isSet = false;
    m_urn_isValid = false;

    m_description_isSet = false;
    m_description_isValid = false;

    m_actions_isSet = false;
    m_actions_isValid = false;

    m_attributes_isSet = false;
    m_attributes_isValid = false;
}

void OAIResourceRead::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIResourceRead::fromJsonObject(QJsonObject json) {

    m_key_isValid = ::OpenAPI::fromJsonValue(key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_organization_id_isValid = ::OpenAPI::fromJsonValue(organization_id, json[QString("organization_id")]);
    m_organization_id_isSet = !json[QString("organization_id")].isNull() && m_organization_id_isValid;

    m_project_id_isValid = ::OpenAPI::fromJsonValue(project_id, json[QString("project_id")]);
    m_project_id_isSet = !json[QString("project_id")].isNull() && m_project_id_isValid;

    m_environment_id_isValid = ::OpenAPI::fromJsonValue(environment_id, json[QString("environment_id")]);
    m_environment_id_isSet = !json[QString("environment_id")].isNull() && m_environment_id_isValid;

    m_created_at_isValid = ::OpenAPI::fromJsonValue(created_at, json[QString("created_at")]);
    m_created_at_isSet = !json[QString("created_at")].isNull() && m_created_at_isValid;

    m_updated_at_isValid = ::OpenAPI::fromJsonValue(updated_at, json[QString("updated_at")]);
    m_updated_at_isSet = !json[QString("updated_at")].isNull() && m_updated_at_isValid;

    m_name_isValid = ::OpenAPI::fromJsonValue(name, json[QString("name")]);
    m_name_isSet = !json[QString("name")].isNull() && m_name_isValid;

    m_urn_isValid = ::OpenAPI::fromJsonValue(urn, json[QString("urn")]);
    m_urn_isSet = !json[QString("urn")].isNull() && m_urn_isValid;

    m_description_isValid = ::OpenAPI::fromJsonValue(description, json[QString("description")]);
    m_description_isSet = !json[QString("description")].isNull() && m_description_isValid;

    m_actions_isValid = ::OpenAPI::fromJsonValue(actions, json[QString("actions")]);
    m_actions_isSet = !json[QString("actions")].isNull() && m_actions_isValid;

    m_attributes_isValid = ::OpenAPI::fromJsonValue(attributes, json[QString("attributes")]);
    m_attributes_isSet = !json[QString("attributes")].isNull() && m_attributes_isValid;
}

QString OAIResourceRead::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIResourceRead::asJsonObject() const {
    QJsonObject obj;
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(key));
    }
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_organization_id_isSet) {
        obj.insert(QString("organization_id"), ::OpenAPI::toJsonValue(organization_id));
    }
    if (m_project_id_isSet) {
        obj.insert(QString("project_id"), ::OpenAPI::toJsonValue(project_id));
    }
    if (m_environment_id_isSet) {
        obj.insert(QString("environment_id"), ::OpenAPI::toJsonValue(environment_id));
    }
    if (m_created_at_isSet) {
        obj.insert(QString("created_at"), ::OpenAPI::toJsonValue(created_at));
    }
    if (m_updated_at_isSet) {
        obj.insert(QString("updated_at"), ::OpenAPI::toJsonValue(updated_at));
    }
    if (m_name_isSet) {
        obj.insert(QString("name"), ::OpenAPI::toJsonValue(name));
    }
    if (m_urn_isSet) {
        obj.insert(QString("urn"), ::OpenAPI::toJsonValue(urn));
    }
    if (m_description_isSet) {
        obj.insert(QString("description"), ::OpenAPI::toJsonValue(description));
    }
    if (actions.size() > 0) {
        obj.insert(QString("actions"), ::OpenAPI::toJsonValue(actions));
    }
    if (attributes.size() > 0) {
        obj.insert(QString("attributes"), ::OpenAPI::toJsonValue(attributes));
    }
    return obj;
}

QString OAIResourceRead::getKey() const {
    return key;
}
void OAIResourceRead::setKey(const QString &key) {
    this->key = key;
    this->m_key_isSet = true;
}

bool OAIResourceRead::is_key_Set() const{
    return m_key_isSet;
}

bool OAIResourceRead::is_key_Valid() const{
    return m_key_isValid;
}

QString OAIResourceRead::getId() const {
    return id;
}
void OAIResourceRead::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIResourceRead::is_id_Set() const{
    return m_id_isSet;
}

bool OAIResourceRead::is_id_Valid() const{
    return m_id_isValid;
}

QString OAIResourceRead::getOrganizationId() const {
    return organization_id;
}
void OAIResourceRead::setOrganizationId(const QString &organization_id) {
    this->organization_id = organization_id;
    this->m_organization_id_isSet = true;
}

bool OAIResourceRead::is_organization_id_Set() const{
    return m_organization_id_isSet;
}

bool OAIResourceRead::is_organization_id_Valid() const{
    return m_organization_id_isValid;
}

QString OAIResourceRead::getProjectId() const {
    return project_id;
}
void OAIResourceRead::setProjectId(const QString &project_id) {
    this->project_id = project_id;
    this->m_project_id_isSet = true;
}

bool OAIResourceRead::is_project_id_Set() const{
    return m_project_id_isSet;
}

bool OAIResourceRead::is_project_id_Valid() const{
    return m_project_id_isValid;
}

QString OAIResourceRead::getEnvironmentId() const {
    return environment_id;
}
void OAIResourceRead::setEnvironmentId(const QString &environment_id) {
    this->environment_id = environment_id;
    this->m_environment_id_isSet = true;
}

bool OAIResourceRead::is_environment_id_Set() const{
    return m_environment_id_isSet;
}

bool OAIResourceRead::is_environment_id_Valid() const{
    return m_environment_id_isValid;
}

QDateTime OAIResourceRead::getCreatedAt() const {
    return created_at;
}
void OAIResourceRead::setCreatedAt(const QDateTime &created_at) {
    this->created_at = created_at;
    this->m_created_at_isSet = true;
}

bool OAIResourceRead::is_created_at_Set() const{
    return m_created_at_isSet;
}

bool OAIResourceRead::is_created_at_Valid() const{
    return m_created_at_isValid;
}

QDateTime OAIResourceRead::getUpdatedAt() const {
    return updated_at;
}
void OAIResourceRead::setUpdatedAt(const QDateTime &updated_at) {
    this->updated_at = updated_at;
    this->m_updated_at_isSet = true;
}

bool OAIResourceRead::is_updated_at_Set() const{
    return m_updated_at_isSet;
}

bool OAIResourceRead::is_updated_at_Valid() const{
    return m_updated_at_isValid;
}

QString OAIResourceRead::getName() const {
    return name;
}
void OAIResourceRead::setName(const QString &name) {
    this->name = name;
    this->m_name_isSet = true;
}

bool OAIResourceRead::is_name_Set() const{
    return m_name_isSet;
}

bool OAIResourceRead::is_name_Valid() const{
    return m_name_isValid;
}

QString OAIResourceRead::getUrn() const {
    return urn;
}
void OAIResourceRead::setUrn(const QString &urn) {
    this->urn = urn;
    this->m_urn_isSet = true;
}

bool OAIResourceRead::is_urn_Set() const{
    return m_urn_isSet;
}

bool OAIResourceRead::is_urn_Valid() const{
    return m_urn_isValid;
}

QString OAIResourceRead::getDescription() const {
    return description;
}
void OAIResourceRead::setDescription(const QString &description) {
    this->description = description;
    this->m_description_isSet = true;
}

bool OAIResourceRead::is_description_Set() const{
    return m_description_isSet;
}

bool OAIResourceRead::is_description_Valid() const{
    return m_description_isValid;
}

QMap<QString, OAIActionBlockRead> OAIResourceRead::getActions() const {
    return actions;
}
void OAIResourceRead::setActions(const QMap<QString, OAIActionBlockRead> &actions) {
    this->actions = actions;
    this->m_actions_isSet = true;
}

bool OAIResourceRead::is_actions_Set() const{
    return m_actions_isSet;
}

bool OAIResourceRead::is_actions_Valid() const{
    return m_actions_isValid;
}

QMap<QString, OAIAttributeBlockRead> OAIResourceRead::getAttributes() const {
    return attributes;
}
void OAIResourceRead::setAttributes(const QMap<QString, OAIAttributeBlockRead> &attributes) {
    this->attributes = attributes;
    this->m_attributes_isSet = true;
}

bool OAIResourceRead::is_attributes_Set() const{
    return m_attributes_isSet;
}

bool OAIResourceRead::is_attributes_Valid() const{
    return m_attributes_isValid;
}

bool OAIResourceRead::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_organization_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_project_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_environment_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_created_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_updated_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_urn_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_description_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (actions.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (attributes.size() > 0) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIResourceRead::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_key_isValid && m_id_isValid && m_organization_id_isValid && m_project_id_isValid && m_environment_id_isValid && m_created_at_isValid && m_updated_at_isValid && m_name_isValid && true;
}

} // namespace OpenAPI
