/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserCreate.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUserCreate::OAIUserCreate(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserCreate::OAIUserCreate() {
    this->initializeModel();
}

OAIUserCreate::~OAIUserCreate() {}

void OAIUserCreate::initializeModel() {

    m_key_isSet = false;
    m_key_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;

    m_first_name_isSet = false;
    m_first_name_isValid = false;

    m_last_name_isSet = false;
    m_last_name_isValid = false;

    m_attributes_isSet = false;
    m_attributes_isValid = false;
}

void OAIUserCreate::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserCreate::fromJsonObject(QJsonObject json) {

    m_key_isValid = ::OpenAPI::fromJsonValue(key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_email_isValid = ::OpenAPI::fromJsonValue(email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;

    m_first_name_isValid = ::OpenAPI::fromJsonValue(first_name, json[QString("first_name")]);
    m_first_name_isSet = !json[QString("first_name")].isNull() && m_first_name_isValid;

    m_last_name_isValid = ::OpenAPI::fromJsonValue(last_name, json[QString("last_name")]);
    m_last_name_isSet = !json[QString("last_name")].isNull() && m_last_name_isValid;

    m_attributes_isValid = ::OpenAPI::fromJsonValue(attributes, json[QString("attributes")]);
    m_attributes_isSet = !json[QString("attributes")].isNull() && m_attributes_isValid;
}

QString OAIUserCreate::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserCreate::asJsonObject() const {
    QJsonObject obj;
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(key));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::OpenAPI::toJsonValue(email));
    }
    if (m_first_name_isSet) {
        obj.insert(QString("first_name"), ::OpenAPI::toJsonValue(first_name));
    }
    if (m_last_name_isSet) {
        obj.insert(QString("last_name"), ::OpenAPI::toJsonValue(last_name));
    }
    if (m_attributes_isSet) {
        obj.insert(QString("attributes"), ::OpenAPI::toJsonValue(attributes));
    }
    return obj;
}

QString OAIUserCreate::getKey() const {
    return key;
}
void OAIUserCreate::setKey(const QString &key) {
    this->key = key;
    this->m_key_isSet = true;
}

bool OAIUserCreate::is_key_Set() const{
    return m_key_isSet;
}

bool OAIUserCreate::is_key_Valid() const{
    return m_key_isValid;
}

QString OAIUserCreate::getEmail() const {
    return email;
}
void OAIUserCreate::setEmail(const QString &email) {
    this->email = email;
    this->m_email_isSet = true;
}

bool OAIUserCreate::is_email_Set() const{
    return m_email_isSet;
}

bool OAIUserCreate::is_email_Valid() const{
    return m_email_isValid;
}

QString OAIUserCreate::getFirstName() const {
    return first_name;
}
void OAIUserCreate::setFirstName(const QString &first_name) {
    this->first_name = first_name;
    this->m_first_name_isSet = true;
}

bool OAIUserCreate::is_first_name_Set() const{
    return m_first_name_isSet;
}

bool OAIUserCreate::is_first_name_Valid() const{
    return m_first_name_isValid;
}

QString OAIUserCreate::getLastName() const {
    return last_name;
}
void OAIUserCreate::setLastName(const QString &last_name) {
    this->last_name = last_name;
    this->m_last_name_isSet = true;
}

bool OAIUserCreate::is_last_name_Set() const{
    return m_last_name_isSet;
}

bool OAIUserCreate::is_last_name_Valid() const{
    return m_last_name_isValid;
}

OAIObject OAIUserCreate::getAttributes() const {
    return attributes;
}
void OAIUserCreate::setAttributes(const OAIObject &attributes) {
    this->attributes = attributes;
    this->m_attributes_isSet = true;
}

bool OAIUserCreate::is_attributes_Set() const{
    return m_attributes_isSet;
}

bool OAIUserCreate::is_attributes_Valid() const{
    return m_attributes_isValid;
}

bool OAIUserCreate::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_first_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_last_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_attributes_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserCreate::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_key_isValid && true;
}

} // namespace OpenAPI
