/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIUserObject.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIUserObject::OAIUserObject(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIUserObject::OAIUserObject() {
    this->initializeModel();
}

OAIUserObject::~OAIUserObject() {}

void OAIUserObject::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_key_isSet = false;
    m_key_isValid = false;

    m_email_isSet = false;
    m_email_isValid = false;

    m_first_name_isSet = false;
    m_first_name_isValid = false;

    m_last_name_isSet = false;
    m_last_name_isValid = false;

    m_attributes_isSet = false;
    m_attributes_isValid = false;

    m_assigned_roles_isSet = false;
    m_assigned_roles_isValid = false;

    m_created_at_isSet = false;
    m_created_at_isValid = false;

    m_updated_at_isSet = false;
    m_updated_at_isValid = false;
}

void OAIUserObject::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIUserObject::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_key_isValid = ::OpenAPI::fromJsonValue(key, json[QString("key")]);
    m_key_isSet = !json[QString("key")].isNull() && m_key_isValid;

    m_email_isValid = ::OpenAPI::fromJsonValue(email, json[QString("email")]);
    m_email_isSet = !json[QString("email")].isNull() && m_email_isValid;

    m_first_name_isValid = ::OpenAPI::fromJsonValue(first_name, json[QString("first_name")]);
    m_first_name_isSet = !json[QString("first_name")].isNull() && m_first_name_isValid;

    m_last_name_isValid = ::OpenAPI::fromJsonValue(last_name, json[QString("last_name")]);
    m_last_name_isSet = !json[QString("last_name")].isNull() && m_last_name_isValid;

    m_attributes_isValid = ::OpenAPI::fromJsonValue(attributes, json[QString("attributes")]);
    m_attributes_isSet = !json[QString("attributes")].isNull() && m_attributes_isValid;

    m_assigned_roles_isValid = ::OpenAPI::fromJsonValue(assigned_roles, json[QString("assigned_roles")]);
    m_assigned_roles_isSet = !json[QString("assigned_roles")].isNull() && m_assigned_roles_isValid;

    m_created_at_isValid = ::OpenAPI::fromJsonValue(created_at, json[QString("created_at")]);
    m_created_at_isSet = !json[QString("created_at")].isNull() && m_created_at_isValid;

    m_updated_at_isValid = ::OpenAPI::fromJsonValue(updated_at, json[QString("updated_at")]);
    m_updated_at_isSet = !json[QString("updated_at")].isNull() && m_updated_at_isValid;
}

QString OAIUserObject::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIUserObject::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_key_isSet) {
        obj.insert(QString("key"), ::OpenAPI::toJsonValue(key));
    }
    if (m_email_isSet) {
        obj.insert(QString("email"), ::OpenAPI::toJsonValue(email));
    }
    if (m_first_name_isSet) {
        obj.insert(QString("first_name"), ::OpenAPI::toJsonValue(first_name));
    }
    if (m_last_name_isSet) {
        obj.insert(QString("last_name"), ::OpenAPI::toJsonValue(last_name));
    }
    if (m_attributes_isSet) {
        obj.insert(QString("attributes"), ::OpenAPI::toJsonValue(attributes));
    }
    if (assigned_roles.size() > 0) {
        obj.insert(QString("assigned_roles"), ::OpenAPI::toJsonValue(assigned_roles));
    }
    if (m_created_at_isSet) {
        obj.insert(QString("created_at"), ::OpenAPI::toJsonValue(created_at));
    }
    if (m_updated_at_isSet) {
        obj.insert(QString("updated_at"), ::OpenAPI::toJsonValue(updated_at));
    }
    return obj;
}

QString OAIUserObject::getId() const {
    return id;
}
void OAIUserObject::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIUserObject::is_id_Set() const{
    return m_id_isSet;
}

bool OAIUserObject::is_id_Valid() const{
    return m_id_isValid;
}

QString OAIUserObject::getKey() const {
    return key;
}
void OAIUserObject::setKey(const QString &key) {
    this->key = key;
    this->m_key_isSet = true;
}

bool OAIUserObject::is_key_Set() const{
    return m_key_isSet;
}

bool OAIUserObject::is_key_Valid() const{
    return m_key_isValid;
}

QString OAIUserObject::getEmail() const {
    return email;
}
void OAIUserObject::setEmail(const QString &email) {
    this->email = email;
    this->m_email_isSet = true;
}

bool OAIUserObject::is_email_Set() const{
    return m_email_isSet;
}

bool OAIUserObject::is_email_Valid() const{
    return m_email_isValid;
}

QString OAIUserObject::getFirstName() const {
    return first_name;
}
void OAIUserObject::setFirstName(const QString &first_name) {
    this->first_name = first_name;
    this->m_first_name_isSet = true;
}

bool OAIUserObject::is_first_name_Set() const{
    return m_first_name_isSet;
}

bool OAIUserObject::is_first_name_Valid() const{
    return m_first_name_isValid;
}

QString OAIUserObject::getLastName() const {
    return last_name;
}
void OAIUserObject::setLastName(const QString &last_name) {
    this->last_name = last_name;
    this->m_last_name_isSet = true;
}

bool OAIUserObject::is_last_name_Set() const{
    return m_last_name_isSet;
}

bool OAIUserObject::is_last_name_Valid() const{
    return m_last_name_isValid;
}

OAIObject OAIUserObject::getAttributes() const {
    return attributes;
}
void OAIUserObject::setAttributes(const OAIObject &attributes) {
    this->attributes = attributes;
    this->m_attributes_isSet = true;
}

bool OAIUserObject::is_attributes_Set() const{
    return m_attributes_isSet;
}

bool OAIUserObject::is_attributes_Valid() const{
    return m_attributes_isValid;
}

QList<QString> OAIUserObject::getAssignedRoles() const {
    return assigned_roles;
}
void OAIUserObject::setAssignedRoles(const QList<QString> &assigned_roles) {
    this->assigned_roles = assigned_roles;
    this->m_assigned_roles_isSet = true;
}

bool OAIUserObject::is_assigned_roles_Set() const{
    return m_assigned_roles_isSet;
}

bool OAIUserObject::is_assigned_roles_Valid() const{
    return m_assigned_roles_isValid;
}

QDateTime OAIUserObject::getCreatedAt() const {
    return created_at;
}
void OAIUserObject::setCreatedAt(const QDateTime &created_at) {
    this->created_at = created_at;
    this->m_created_at_isSet = true;
}

bool OAIUserObject::is_created_at_Set() const{
    return m_created_at_isSet;
}

bool OAIUserObject::is_created_at_Valid() const{
    return m_created_at_isValid;
}

QDateTime OAIUserObject::getUpdatedAt() const {
    return updated_at;
}
void OAIUserObject::setUpdatedAt(const QDateTime &updated_at) {
    this->updated_at = updated_at;
    this->m_updated_at_isSet = true;
}

bool OAIUserObject::is_updated_at_Set() const{
    return m_updated_at_isSet;
}

bool OAIUserObject::is_updated_at_Valid() const{
    return m_updated_at_isValid;
}

bool OAIUserObject::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_key_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_email_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_first_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_last_name_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_attributes_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (assigned_roles.size() > 0) {
            isObjectUpdated = true;
            break;
        }

        if (m_created_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_updated_at_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIUserObject::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_key_isValid && m_created_at_isValid && m_updated_at_isValid && true;
}

} // namespace OpenAPI
