/**
 * Permit.io API
 *  Authorization as a service 
 *
 * The version of the OpenAPI document: 2.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAIWebhookRead.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAIWebhookRead::OAIWebhookRead(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAIWebhookRead::OAIWebhookRead() {
    this->initializeModel();
}

OAIWebhookRead::~OAIWebhookRead() {}

void OAIWebhookRead::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_organization_id_isSet = false;
    m_organization_id_isValid = false;

    m_project_id_isSet = false;
    m_project_id_isValid = false;

    m_environment_id_isSet = false;
    m_environment_id_isValid = false;

    m_created_at_isSet = false;
    m_created_at_isValid = false;

    m_updated_at_isSet = false;
    m_updated_at_isValid = false;

    m_url_isSet = false;
    m_url_isValid = false;
}

void OAIWebhookRead::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAIWebhookRead::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_organization_id_isValid = ::OpenAPI::fromJsonValue(organization_id, json[QString("organization_id")]);
    m_organization_id_isSet = !json[QString("organization_id")].isNull() && m_organization_id_isValid;

    m_project_id_isValid = ::OpenAPI::fromJsonValue(project_id, json[QString("project_id")]);
    m_project_id_isSet = !json[QString("project_id")].isNull() && m_project_id_isValid;

    m_environment_id_isValid = ::OpenAPI::fromJsonValue(environment_id, json[QString("environment_id")]);
    m_environment_id_isSet = !json[QString("environment_id")].isNull() && m_environment_id_isValid;

    m_created_at_isValid = ::OpenAPI::fromJsonValue(created_at, json[QString("created_at")]);
    m_created_at_isSet = !json[QString("created_at")].isNull() && m_created_at_isValid;

    m_updated_at_isValid = ::OpenAPI::fromJsonValue(updated_at, json[QString("updated_at")]);
    m_updated_at_isSet = !json[QString("updated_at")].isNull() && m_updated_at_isValid;

    m_url_isValid = ::OpenAPI::fromJsonValue(url, json[QString("url")]);
    m_url_isSet = !json[QString("url")].isNull() && m_url_isValid;
}

QString OAIWebhookRead::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAIWebhookRead::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(id));
    }
    if (m_organization_id_isSet) {
        obj.insert(QString("organization_id"), ::OpenAPI::toJsonValue(organization_id));
    }
    if (m_project_id_isSet) {
        obj.insert(QString("project_id"), ::OpenAPI::toJsonValue(project_id));
    }
    if (m_environment_id_isSet) {
        obj.insert(QString("environment_id"), ::OpenAPI::toJsonValue(environment_id));
    }
    if (m_created_at_isSet) {
        obj.insert(QString("created_at"), ::OpenAPI::toJsonValue(created_at));
    }
    if (m_updated_at_isSet) {
        obj.insert(QString("updated_at"), ::OpenAPI::toJsonValue(updated_at));
    }
    if (m_url_isSet) {
        obj.insert(QString("url"), ::OpenAPI::toJsonValue(url));
    }
    return obj;
}

QString OAIWebhookRead::getId() const {
    return id;
}
void OAIWebhookRead::setId(const QString &id) {
    this->id = id;
    this->m_id_isSet = true;
}

bool OAIWebhookRead::is_id_Set() const{
    return m_id_isSet;
}

bool OAIWebhookRead::is_id_Valid() const{
    return m_id_isValid;
}

QString OAIWebhookRead::getOrganizationId() const {
    return organization_id;
}
void OAIWebhookRead::setOrganizationId(const QString &organization_id) {
    this->organization_id = organization_id;
    this->m_organization_id_isSet = true;
}

bool OAIWebhookRead::is_organization_id_Set() const{
    return m_organization_id_isSet;
}

bool OAIWebhookRead::is_organization_id_Valid() const{
    return m_organization_id_isValid;
}

QString OAIWebhookRead::getProjectId() const {
    return project_id;
}
void OAIWebhookRead::setProjectId(const QString &project_id) {
    this->project_id = project_id;
    this->m_project_id_isSet = true;
}

bool OAIWebhookRead::is_project_id_Set() const{
    return m_project_id_isSet;
}

bool OAIWebhookRead::is_project_id_Valid() const{
    return m_project_id_isValid;
}

QString OAIWebhookRead::getEnvironmentId() const {
    return environment_id;
}
void OAIWebhookRead::setEnvironmentId(const QString &environment_id) {
    this->environment_id = environment_id;
    this->m_environment_id_isSet = true;
}

bool OAIWebhookRead::is_environment_id_Set() const{
    return m_environment_id_isSet;
}

bool OAIWebhookRead::is_environment_id_Valid() const{
    return m_environment_id_isValid;
}

QDateTime OAIWebhookRead::getCreatedAt() const {
    return created_at;
}
void OAIWebhookRead::setCreatedAt(const QDateTime &created_at) {
    this->created_at = created_at;
    this->m_created_at_isSet = true;
}

bool OAIWebhookRead::is_created_at_Set() const{
    return m_created_at_isSet;
}

bool OAIWebhookRead::is_created_at_Valid() const{
    return m_created_at_isValid;
}

QDateTime OAIWebhookRead::getUpdatedAt() const {
    return updated_at;
}
void OAIWebhookRead::setUpdatedAt(const QDateTime &updated_at) {
    this->updated_at = updated_at;
    this->m_updated_at_isSet = true;
}

bool OAIWebhookRead::is_updated_at_Set() const{
    return m_updated_at_isSet;
}

bool OAIWebhookRead::is_updated_at_Valid() const{
    return m_updated_at_isValid;
}

QString OAIWebhookRead::getUrl() const {
    return url;
}
void OAIWebhookRead::setUrl(const QString &url) {
    this->url = url;
    this->m_url_isSet = true;
}

bool OAIWebhookRead::is_url_Set() const{
    return m_url_isSet;
}

bool OAIWebhookRead::is_url_Valid() const{
    return m_url_isValid;
}

bool OAIWebhookRead::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_organization_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_project_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_environment_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_created_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_updated_at_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_url_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAIWebhookRead::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_organization_id_isValid && m_project_id_isValid && m_environment_id_isValid && m_created_at_isValid && m_updated_at_isValid && m_url_isValid && true;
}

} // namespace OpenAPI
